from typing import Annotated, Literal
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage, AIMessage
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode

from app.config import settings
from app.agent.state import AgentState
from app.agent.tools import jarvis_tools

SYSTEM_PROMPT = """You are Jarvis, an intelligent AI Copilot and conversational assistant integrated with Microsoft 365.

CRITICAL BEHAVIOR AND TOOL USAGE RULES:

1. GENERAL ASSISTANT & CONVERSATIONAL CHAT (NO TOOLS):
   - For greetings (e.g., "hi", "hello", "hey"), casual questions (e.g., "can you fly?", "who are you?", "how are you?"), explanations, coding, brainstorming, or general conversation, RESPOND DIRECTLY as a smart, friendly AI assistant.
   - DO NOT invoke any tools for general conversation or questions.

2. EXPLICIT TASK EXECUTION ONLY:
   - ONLY use Microsoft 365 tools (emails, calendar, to-do tasks) when the user EXPLICITLY asks you to perform a specific task (e.g., "fetch my emails", "create a meeting", "add a task", "draft an email to john@example.com").
   - NEVER create email drafts, calendar events, or tasks automatically or without the user's explicit command.

3. EMAIL DRAFTING SAFETY:
   - You CANNOT send emails directly.
   - If the user explicitly asks you to draft or send an email, create an email draft using `create_email_draft` or `create_reply_draft`.
   - Never draft an email unless requested!

4. UNSUPPORTED OR UNCLEAR COMMANDS:
   - If a request is unclear, ambiguous, or asks for something you cannot do (for example, deleting all drafts when no delete draft tool exists), DO NOT call unrelated tools or attempt random actions.
   - Simply state clearly what you can or cannot do, or ask the user for clarification (e.g., "I cannot delete email drafts automatically, but you can manage them in your Mailbox tab.").

Maintain a sleek, helpful, professional, and natural Jarvis persona. Be concise and smart.
"""

def should_continue(state: AgentState) -> Literal["tools", "__end__"]:
    """Determine whether to continue to tools or end the conversation."""
    messages = state.get("messages", [])
    last_message = messages[-1]
    
    # If the LLM makes a tool call, we transition to the tools node
    if last_message.tool_calls:
        return "tools"
    
    # Otherwise, we end and return the final text
    return "__end__"

def call_model(state: AgentState):
    """Invoke the Groq LLM to reason and decide the next action."""
    messages = state.get("messages", [])
    session_id = state.get("session_id", "")
    
    # Separate system messages from user/assistant chat history
    non_system_messages = [m for m in messages if not isinstance(m, SystemMessage)]
    
    from datetime import datetime, timezone
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    system_messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        SystemMessage(content=f"Current Date & Time context: {now_utc}. Default timezone unless specified is Asia/Karachi (PKT, UTC+5) or UTC."),
        SystemMessage(content=f"IMPORTANT: Always pass this exact session_id to your tools: '{session_id}'")
    ]
    
    full_messages = system_messages + non_system_messages
    
    # Models to try with automatic fallback on RateLimitError (429)
    models_to_try = [
        "llama-3.1-8b-instant",
        "llama-3.3-70b-versatile",
        "mixtral-8x7b-32768"
    ]
    
    last_exception = None
    for model_name in models_to_try:
        try:
            llm = ChatGroq(
                groq_api_key=settings.GROQ_API_KEY,
                model_name=model_name,
                max_tokens=500
            )
            llm_with_tools = llm.bind_tools(jarvis_tools)
            response = llm_with_tools.invoke(full_messages)
            return {"messages": [response]}
        except Exception as e:
            last_exception = e
            if "RateLimitError" in type(e).__name__ or "429" in str(e) or "rate_limit" in str(e).lower():
                continue
            raise e
            
    if last_exception:
        raise last_exception

def inject_session_id(state: AgentState):
    """Injects the session_id into the tool calls generated by the LLM."""
    messages = state.get("messages", [])
    session_id = state.get("session_id", "")
    if not messages:
        return {}
        
    last_message = messages[-1]
    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        new_tool_calls = []
        for tc in last_message.tool_calls:
            tc_args = dict(tc["args"])
            tc_args["session_id"] = session_id
            new_tool_calls.append({
                "name": tc["name"],
                "args": tc_args,
                "id": tc["id"]
            })
        
        new_message = AIMessage(
            content=last_message.content,
            tool_calls=new_tool_calls,
            id=last_message.id
        )
        return {"messages": [new_message]}
    
    return {}



def build_graph():
    """Constructs the LangGraph state graph for Jarvis."""
    workflow = StateGraph(AgentState)
    
    # Define the nodes
    workflow.add_node("agent", call_model)
    workflow.add_node("inject_session", inject_session_id)
    
    # We use LangGraph's prebuilt ToolNode to automatically execute the selected tools
    tool_node = ToolNode(jarvis_tools)
    workflow.add_node("tools", tool_node)
    
    # Set the entry point
    workflow.set_entry_point("agent")
    
    # Add conditional edges from the agent node
    workflow.add_conditional_edges(
        "agent",
        should_continue,
        {
            "tools": "inject_session",
            "__end__": END
        }
    )
    
    workflow.add_edge("inject_session", "tools")
    
    # Once tools are done executing, loop back to the agent to interpret the result
    workflow.add_edge("tools", "agent")
    
    # Compile the graph
    return workflow.compile()

# Global compiled graph instance
jarvis_agent = build_graph()
